#version: "3.8"

services:
  kb-dev:
    build: .
    container_name: kb-development
    volumes:
      # 로컬 코드 디렉토리를 컨테이너의 /project/main에 마운트
      - ./main:/project/main
    ports:
      # Jupyter notebook 포트
      - "8888:8888"
      # 개발용 포트 (필요에 따라 추가)
      - "7860:7860"
    environment:
      # OpenAI API 키 등 환경변수 설정
      - PYTHONPATH=/project/main
      - DB_HOST=pgvector-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - pgvector-db

    # 컨테이너가 종료되지 않도록 설정
    tty: true
    stdin_open: true

    # 재시작 정책
#    restart: unless-stopped

  pgvector-db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped

volumes:
  pgdata: